services:
  postgres:
    image: postgres:16
    container_name: postgresql
    env_file:
      - .postgres.env

  restaurant-service:
    build:
      context: ./restaurant
      dockerfile: restaurant.dockerfile
    container_name: restaurant-service
    env_file:
      - ./restaurant/.env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"

volumes:
  mongo_data:
  mysql_data:
